name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, description: What happened? }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to Reproduce }
  - type: input
    id: version
    attributes: { label: Version, placeholder: v0.1.0 }
