name: Feature request
description: Propose a new capability or enhancement
title: "[feat]: "
labels: ["kind/feature", "prio/med"]
assignees: []
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Who benefits?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: High-level description; config examples; acceptance criteria
      placeholder: |
        - As a ...
        - I want ...
        - So that ...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Considered alternatives and trade-offs
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - orchestrator
        - agents
        - models
        - tools
        - memory
        - helm
        - docs

name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes: { label: Motivation, description: Why is this needed? }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposal }
