name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install
        run: |
          pip install -e .
          pip install pytest pytest-cov ruff
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest --cov=swe_ai_fleet --cov-report=xml
  it_e2e:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: pip install -e . pytest pyyaml
      - run: pytest -m "integration or e2e" -q
