name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install
        run: |
          pip install -e .
          pip install pytest pytest-cov ruff
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest -m "not e2e and not integration" --cov=swe_ai_fleet --cov-report=xml
      - name: SonarQube Scan (disabled for now)
        if: false  # Enable by providing SONAR_TOKEN and removing this condition
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  integration:
    if: false  # Disabled for now; placeholder for future implementation
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests are disabled for now"
